const CONFIG={url:"https://jiupaabevawvnpwyjvjx.supabase.co",key:"sb_publishable_gOi9DT7HpLMZsR7w4uI0wA_S72AjUad",email:"dashboard@homefrance.internal"};
const db=supabase.createClient(CONFIG.url,CONFIG.key),$=id=>document.getElementById(id);let proposals=[],calendar=[],events=[],selected,editingProposalId=null,proposalPage=1;const PROPOSALS_PER_PAGE=20;
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const months=["January","February","March","April","May","June","July","August","September","October","November","December"],weekdays=["MON","TUE","WED","THU","FRI","SAT","SUN"];
function toast(s){$("toast").textContent=s;$("toast").classList.remove("hidden");setTimeout(()=>$("toast").classList.add("hidden"),2400)}function signedIn(v){$("login").classList.toggle("hidden",v);$("app").classList.toggle("hidden",!v)}
function more(x,actions=""){return `<details><summary>See more</summary><div class="more">${x.description?`<b>Description</b><p>${esc(x.description).replace(/\n/g,"<br>")}</p>`:""}<b>Must cover</b><ul>${(x.must_cover||[]).map(p=>`<li>${esc(p)}</li>`).join("")}</ul>${x.source_url?`<a href="${esc(x.source_url)}" target="_blank" rel="noopener">Open source ↗</a>`:""}${actions}</div></details>`}
function renderProposals(){
 $("proposalCount").textContent=`${proposals.length} / 100`;
 const totalPages=Math.max(1,Math.ceil(proposals.length/PROPOSALS_PER_PAGE));if(proposalPage>totalPages)proposalPage=totalPages;
 const start=(proposalPage-1)*PROPOSALS_PER_PAGE,pageItems=proposals.slice(start,start+PROPOSALS_PER_PAGE);
 const cards=pageItems.length?pageItems.map(p=>`<article class="proposal ${p.is_urgent?"urgent":""}"><div class="code">${esc(p.code)}</div><div class="${p.language==="fa"?"fa":""}"><div class="subject">${esc(p.subject)}</div><div class="source">${esc(p.source_label)}</div></div><div class="badges">${p.is_urgent?'<span class="badge urgent-b">URGENT</span>':""}${p.is_audience_priority?'<span class="badge audience">AUDIENCE PRIORITY</span>':""}<span class="badge language">${p.language==="fa"?"فارسی":"ENGLISH"}</span></div>${more(p)}<div class="row-actions"><button class="btn schedule-proposal" data-id="${p.id}">Add to Calendar</button><button class="btn pale urgent-toggle" data-id="${p.id}" data-urgent="${p.is_urgent}">${p.is_urgent?"Remove Urgent":"Urgent"}</button><button class="btn pale audience-toggle" data-id="${p.id}" data-audience="${p.is_audience_priority}">${p.is_audience_priority?"Remove Audience Priority":"Audience Priority"}</button><button class="btn pale edit-proposal" data-id="${p.id}">Edit</button><button class="btn danger delete-proposal" data-id="${p.id}">Delete</button></div></article>`).join(""):'<div class="empty">No active proposals.</div>';
 const pager=proposals.length>PROPOSALS_PER_PAGE?`<div class="row-actions" style="justify-content:center;margin-top:18px"><button class="btn pale proposal-prev" ${proposalPage===1?"disabled":""}>← Previous 20</button>${Array.from({length:totalPages},(_,i)=>`<button class="btn ${proposalPage===i+1?"":"pale"} proposal-page" data-page="${i+1}">${i+1}</button>`).join("")}<button class="btn pale proposal-next" ${proposalPage===totalPages?"disabled":""}>Next 20 →</button></div>`:"";
 $("proposals").innerHTML=cards+pager;
 document.querySelectorAll(".schedule-proposal").forEach(b=>b.onclick=()=>openSchedule("proposal",b.dataset.id));document.querySelectorAll(".urgent-toggle").forEach(b=>b.onclick=()=>toggleUrgent(b.dataset.id,b.dataset.urgent!=="true"));document.querySelectorAll(".audience-toggle").forEach(b=>b.onclick=()=>toggleAudience(b.dataset.id,b.dataset.audience!=="true"));document.querySelectorAll(".edit-proposal").forEach(b=>b.onclick=()=>openProposalForm(b.dataset.id));document.querySelectorAll(".delete-proposal").forEach(b=>b.onclick=()=>deleteProposal(b.dataset.id));document.querySelectorAll(".proposal-page").forEach(b=>b.onclick=()=>{proposalPage=Number(b.dataset.page);renderProposals()});const prev=document.querySelector(".proposal-prev"),next=document.querySelector(".proposal-next");if(prev)prev.onclick=()=>{if(proposalPage>1){proposalPage--;renderProposals()}};if(next)next.onclick=()=>{if(proposalPage<totalPages){proposalPage++;renderProposals()}}
}
async function toggleUrgent(id,v){const{error}=await db.from("proposals").update({is_urgent:v}).eq("id",id);if(error)return toast(error.message);await load();toast(v?"Marked urgent":"Urgent removed")}async function toggleAudience(id,v){const{error}=await db.from("proposals").update({is_audience_priority:v}).eq("id",id);if(error)return toast(error.message);await load();toast(v?"Marked audience priority":"Audience priority removed")}
function openProposalForm(id=null){editingProposalId=id;const p=id?proposals.find(x=>x.id===id):null;$("proposalModalTitle").textContent=p?"Edit Proposal":"Add Proposal";$("proposalTitle").value=p?.subject||"";$("proposalDescription").value=p?.description||"";$("proposalModal").classList.remove("hidden");setTimeout(()=>$("proposalTitle").focus(),50)}
async function deleteProposal(id){const p=proposals.find(x=>x.id===id);if(!p||!confirm(`Delete ${p.code} · ${p.subject}? This cannot be undone.`))return;const{error}=await db.from("proposals").delete().eq("id",id);if(error)return toast(error.message);await load();toast(`${p.code} deleted`)}
function renderEvents(){$("eventCount").textContent=`${events.length} verified`;$("events").innerHTML=events.length?events.map(e=>`<article class="event"><div class="event-date">${esc(e.date_label)}</div><div class="event-title">${esc(e.title)}</div><div class="event-place">${esc(e.place)}</div><div class="event-angle">${esc(e.content_angle)}</div>${e.source_url?`<a href="${esc(e.source_url)}" target="_blank" rel="noopener">Official source ↗</a>`:""}<div class="row-actions"><button class="btn schedule-event" data-id="${e.id}">Add to Calendar</button></div></article>`).join(""):'<div class="empty">No upcoming events.</div>';document.querySelectorAll(".schedule-event").forEach(b=>b.onclick=()=>openSchedule("event",b.dataset.id))}
function month(y,m){const first=(new Date(y,m,1).getDay()+6)%7,total=new Date(y,m+1,0).getDate(),now=new Date();let cells="";for(let i=0;i<first;i++)cells+='<div class="day blank"></div>';for(let d=1;d<=total;d++){const key=`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`,items=calendar.filter(x=>x.scheduled_date===key),today=now.getFullYear()===y&&now.getMonth()===m&&now.getDate()===d;cells+=`<div class="day ${today?"today":""}"><div class="day-number">${d}</div>${items.map(x=>{const actions=x.proposal_id?`<div class="calendar-actions"><button class="calendar-action reschedule-calendar" data-id="${x.id}">Reschedule</button><button class="calendar-action back-proposal" data-id="${x.id}">Back to Proposal</button></div>`:"";return `<div class="content"><b>${esc(x.code)}</b> · ${esc(x.subject)}<div>${esc(x.platform)}</div>${more(x,actions)}</div>`}).join("")}</div>`}return `<div class="calendar"><div class="calendar-title">${months[m]} ${y}</div><div class="week">${weekdays.map(x=>`<div class="weekday">${x}</div>`).join("")}</div><div class="days">${cells}</div></div>`}
function cleanupCalendarDetail(){document.querySelector(".calendar-detail-backdrop")?.remove();document.body.classList.remove("calendar-detail-open")}
function setupMobileCalendarDetails(){document.querySelectorAll(".content details").forEach(d=>d.addEventListener("toggle",()=>{if(window.innerWidth>700)return;if(!d.open){if(!document.querySelector(".content details[open]"))cleanupCalendarDetail();return}document.querySelectorAll(".content details[open]").forEach(o=>{if(o!==d)o.open=false});const panel=d.querySelector(".more");if(panel&&!panel.querySelector(".calendar-detail-close")){const close=document.createElement("button");close.type="button";close.className="calendar-detail-close";close.setAttribute("aria-label","Close");close.textContent="×";close.onclick=e=>{e.preventDefault();e.stopPropagation();d.open=false};panel.prepend(close)}cleanupCalendarDetail();const backdrop=document.createElement("div");backdrop.className="calendar-detail-backdrop";backdrop.onclick=()=>{d.open=false};document.body.appendChild(backdrop);document.body.classList.add("calendar-detail-open")}))}
function renderCalendar(){const n=new Date(),nx=new Date(n.getFullYear(),n.getMonth()+1,1);$("calendarCount").textContent=`${calendar.length} scheduled`;$("calendars").innerHTML=month(n.getFullYear(),n.getMonth())+month(nx.getFullYear(),nx.getMonth());document.querySelectorAll(".reschedule-calendar").forEach(b=>b.onclick=()=>openReschedule(b.dataset.id));document.querySelectorAll(".back-proposal").forEach(b=>b.onclick=()=>backToProposal(b.dataset.id));setupMobileCalendarDetails()}
async function load(){const[p,c,e]=await Promise.all([db.from("proposals").select("*").is("scheduled_at",null).order("is_urgent",{ascending:false}).order("is_audience_priority",{ascending:false}).order("created_at",{ascending:false}),db.from("calendar_items").select("*").order("scheduled_date"),db.from("upcoming_events").select("*").order("starts_on")]);const error=p.error||c.error||e.error;if(error)throw error;[proposals,calendar,events]=[p.data,c.data,e.data];renderProposals();renderEvents();renderCalendar();$("updated").textContent=`Updated · ${new Date().toLocaleDateString("en-GB")}`}
function openSchedule(type,id){const item=type==="event"?events.find(x=>x.id===id):proposals.find(x=>x.id===id);selected={type,item};$("scheduleSubject").textContent=type==="event"?`Event · ${item.title}`:`${item.code} · ${item.subject}`;$("scheduleDate").min=new Date().toISOString().slice(0,10);$("scheduleDate").value=type==="event"&&item.starts_on&&item.starts_on>=$("scheduleDate").min?item.starts_on:"";$("platform").value="Instagram + YouTube";$("scheduleModal").classList.remove("hidden")}
function openReschedule(id){const item=calendar.find(x=>x.id===id);if(!item)return;selected={type:"calendar",item};$("scheduleSubject").textContent=`Reschedule · ${item.code} · ${item.subject}`;$("scheduleDate").min=new Date().toISOString().slice(0,10);$("scheduleDate").value=item.scheduled_date;$("platform").value=item.platform||"Instagram + YouTube";$("scheduleModal").classList.remove("hidden")}
async function backToProposal(id){const item=calendar.find(x=>x.id===id);if(!item||!item.proposal_id)return;if(!confirm(`Move ${item.code} · ${item.subject} back to Proposal Subjects?`))return;const{error}=await db.rpc("return_calendar_item_to_proposals",{p_calendar_item_id:id});if(error)return toast(error.message);proposalPage=1;await load();toast("Moved back to Proposals")}
$("addProposal").onclick=()=>openProposalForm();$("cancelProposal").onclick=()=>$("proposalModal").classList.add("hidden");$("proposalForm").onsubmit=async e=>{e.preventDefault();const subject=$("proposalTitle").value.trim(),description=$("proposalDescription").value.trim()||null;if(!subject)return;const language=/[؀-ۿ]/.test(subject)?"fa":"en";let error;if(editingProposalId){({error}=await db.from("proposals").update({subject,description,language}).eq("id",editingProposalId))}else{const nums=proposals.map(p=>parseInt(String(p.code||"").replace(/\D/g,""),10)).filter(Number.isFinite),code=`H${(nums.length?Math.max(...nums):0)+1}`;({error}=await db.from("proposals").insert({code,subject,description,language,source_label:"Manual",must_cover:[],is_urgent:false,is_audience_priority:false}));proposalPage=1}if(error)return toast(error.message);$("proposalModal").classList.add("hidden");await load();toast(editingProposalId?"Proposal updated":"Proposal added")};
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginError").textContent="";const{error}=await db.auth.signInWithPassword({email:CONFIG.email,password:$("password").value});if(error)return $("loginError").textContent="Incorrect password or account not configured.";signedIn(true);await load()};$("logout").onclick=async()=>{await db.auth.signOut();signedIn(false)};
$("scheduleForm").onsubmit=async e=>{e.preventDefault();const date=$("scheduleDate").value,platform=$("platform").value;let error;if(selected.type==="proposal")({error}=await db.rpc("schedule_proposal",{p_proposal_id:selected.item.id,p_scheduled_date:date,p_platform:platform}));else if(selected.type==="calendar")({error}=await db.rpc("reschedule_calendar_item",{p_calendar_item_id:selected.item.id,p_scheduled_date:date,p_platform:platform}));else{const ev=selected.item,fa=/[؀-ۿ]/.test(ev.title||"");({error}=await db.from("calendar_items").insert({proposal_id:null,event_id:ev.id,code:"EVENT",subject:ev.title,language:fa?"fa":"en",must_cover:[ev.content_angle,ev.place?`Place: ${ev.place}`:null,ev.date_label?`Event date: ${ev.date_label}`:null].filter(Boolean),source_url:ev.source_url||null,scheduled_date:date,platform}))}if(error)return toast(error.message);const wasReschedule=selected.type==="calendar";$("scheduleModal").classList.add("hidden");await load();toast(wasReschedule?"Rescheduled":"Scheduled")};$("cancelSchedule").onclick=()=>$("scheduleModal").classList.add("hidden");$("changePassword").onclick=()=>$("passwordModal").classList.remove("hidden");$("cancelPassword").onclick=()=>$("passwordModal").classList.add("hidden");$("passwordForm").onsubmit=async e=>{e.preventDefault();const{error}=await db.auth.updateUser({password:$("newPassword").value});if(error)return toast(error.message);$("newPassword").value="";$("passwordModal").classList.add("hidden");toast("Password updated")};(async()=>{const{data}=await db.auth.getSession();if(data.session){signedIn(true);try{await load()}catch(e){toast(e.message)}}})();